[Connection]
  nifi_host = "https://pi-datamart-proxy.corp.chartercom.com"
  nifi_user = ""
  nifi_pass = ""
  nifi_cert = ""

[Backup]
  backup_path = "/tmp/nifi-backup"
  config_file = "hadoop-ottom8r.toml"
  debug_mode = false
  log_level = "info"
  log_file = "nifi-backup.log"
  mock = false
